=== walid243/walid.abdullah.7e5-m04/ejercicios/Ejercicio5.dtd
<!ELEMENT Empresa (Empleado)+>
<!ELEMENT Empleado (Apellidos, Nombre, (Email | Telefono), Direccion)>
<!ATTLIST Empleado NumEmpleado CDATA #REQUIRED>
<!ELEMENT Apellidos (Apellido1, Apellido2)>
<!ELEMENT Apellido1 (#PCDATA)>
<!ELEMENT Apellido2 (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Direccion EMPTY>
<!ATTLIST Direccion Calle CDATA #REQUIRED>
<!ATTLIST Direccion CP CDATA #REQUIRED>
<!ATTLIST Direccion Ciudad CDATA #IMPLIED>

=== walid243/walid.abdullah.7e5-m04/ejercicios/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa SYSTEM "Ejercicio5.dtd">
<Empresa>
  <Empleado NumEmpleado="12345678">
    <Apellidos>
      <Apellido1>Perez</Apellido1>
      <Apellido2>Lopez</Apellido2>
    </Apellidos>
    <Nombre>Juan</Nombre>
    <Telefono>666 555 444</Telefono>
    <Direccion Calle="arcadio pardiñas" CP="09120" />
  </Empleado>
</Empresa>
